# Generated by Django 4.0.6 on 2023-05-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='animal',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otros', 'Otros')], default='Perro', max_length=8),
        ),
    ]
