# Generated by Django 4.0.6 on 2022-10-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_articulo_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='size',
            field=models.CharField(choices=[('chico', 'Chico hasta 10kg'), ('mediano', 'Mediano entre 10kg/20kg'), ('grande', 'Grande +20kg')], default='chico', max_length=25),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='genero',
            field=models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], default='Macho', max_length=6),
        ),
    ]
