# Generated by Django 4.0.6 on 2022-10-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_alter_articulo_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='date_published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
