# Generated by Django 4.0.6 on 2022-10-22 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_alter_articulo_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
