# Generated by Django 4.0.6 on 2022-10-22 12:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_alter_articulo_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='content_upload',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
