# Generated by Django 4.0.5 on 2023-02-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_alter_articulo_age_alter_articulo_author_and_more'),
        ('APP', '0005_articulo_image1_articulo_image2_alter_articulo_age_and_more'),
    ]

    operations = [
    ]
