# Generated by Django 4.0.5 on 2023-02-09 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_merge_20230202_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='APP.publicador', verbose_name='Autor'),
        ),
    ]
